# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'individ_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 867)
        self.centralwidget = QtWidgets.QWidget(MainWindow)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setText("Поиск")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 20, 421, 31))

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(590, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setText("Сортировка")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(750, 20, 121, 31))

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(930, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setText("Таблицы")

        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(930, 70, 161, 31))

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(930, 140, 141, 51))
        self.pushButton.setText("Добавить")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(930, 240, 141, 51))
        self.pushButton_2.setText("Изменить")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(930, 340, 141, 51))
        self.pushButton_3.setText("Удалить")

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 891, 741))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("Работа с БД")


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.conn = sqlite3.connect("individ.db")
        self.cursor = self.conn.cursor()
        self.load_tables()
        self.ui.comboBox_2.currentTextChanged.connect(self.load_table)

    def load_tables(self):

        self.cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table';"
        )

        tables = self.cursor.fetchall()

        self.ui.comboBox_2.clear()

        for table in tables:
            self.ui.comboBox_2.addItem(table[0])

    def load_table(self, table_name):

        if table_name == "":
            return

        query = f'SELECT * FROM "{table_name}"'
        self.cursor.execute(query)

        data = self.cursor.fetchall()
        columns = [desc[0] for desc in self.cursor.description]

        self.ui.tableWidget.setColumnCount(len(columns))
        self.ui.tableWidget.setRowCount(len(data))

        self.ui.tableWidget.setHorizontalHeaderLabels(columns)

        for row_index, row in enumerate(data):
            for col_index, value in enumerate(row):

                item = QtWidgets.QTableWidgetItem(str(value))
                self.ui.tableWidget.setItem(row_index, col_index, item)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
