# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'individ_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class DynamicDialog(QtWidgets.QDialog):

    def __init__(self, columns, values=None, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Редактирование данных")
        layout = QtWidgets.QFormLayout(self)

        self.line_edits = []
        for i, col in enumerate(columns):
            le = QtWidgets.QLineEdit(self)
            if values:
                le.setText(str(values[i]))
            layout.addRow(col, le)
            self.line_edits.append(le)

        buttons = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.Ok |
            QtWidgets.QDialogButtonBox.Cancel
        )

        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)

        layout.addWidget(buttons)

    def get_data(self):
        return [le.text() for le in self.line_edits]


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 867)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 20, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(590, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(750, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(930, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(930, 70, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(930, 140, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(930, 240, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(930, 340, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(930, 440, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 891, 741))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 26))
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "Работа с БД"))
        self.label.setText(_translate("MainWindow", "Поиск"))
        self.label_2.setText(_translate("MainWindow", "Сортировка"))
        self.label_3.setText(_translate("MainWindow", "Таблицы"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_back.setText(_translate("MainWindow", "Назад"))


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.conn = sqlite3.connect("individ.db")
        self.cursor = self.conn.cursor()

        self.columns = []
        self.current_table = ""

        self.load_tables()

        self.ui.comboBox_2.currentTextChanged.connect(self.load_table)
        self.ui.pushButton.clicked.connect(self.addRow)
        self.ui.pushButton_2.clicked.connect(self.editRow)
        self.ui.pushButton_3.clicked.connect(self.deleteRow)
        self.ui.pushButton_back.clicked.connect(self.back_to_login)

        self.ui.lineEdit.textChanged.connect(self.search_text)
        self.ui.comboBox.currentIndexChanged.connect(self.sort_table)

    def back_to_login(self):
        from login import LoginWindow

        self.login = LoginWindow()
        self.login.show()
        self.close()

    def load_tables(self):
        self.cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';"
        )

        tables = self.cursor.fetchall()
        self.ui.comboBox_2.clear()

        for table in tables:
            self.ui.comboBox_2.addItem(table[0])

    def load_table(self, table_name):
        if table_name == "":
            return

        self.current_table = table_name

        self.cursor.execute(f'SELECT * FROM "{table_name}"')

        data = self.cursor.fetchall()

        self.columns = [desc[0] for desc in self.cursor.description]

        self.ui.tableWidget.setColumnCount(len(self.columns))
        self.ui.tableWidget.setRowCount(len(data))
        self.ui.tableWidget.setHorizontalHeaderLabels(self.columns)

        self.ui.comboBox.clear()
        self.ui.comboBox.addItems(self.columns)

        for i, row in enumerate(data):
            for j, value in enumerate(row):
                item = QtWidgets.QTableWidgetItem(str(value))
                item.setFlags(item.flags() ^ QtCore.Qt.ItemIsEditable)
                self.ui.tableWidget.setItem(i, j, item)

    def addRow(self):
        dialog = DynamicDialog(self.columns)

        if dialog.exec():
            values = dialog.get_data()
            placeholders = ",".join("?" * len(values))
            self.cursor.execute(
                f'INSERT INTO "{self.current_table}" VALUES ({placeholders})',
                values
            )

            self.conn.commit()
            self.load_table(self.current_table)

    def editRow(self):
        selected = self.ui.tableWidget.selectedItems()

        if not selected:
            return

        row = selected[0].row()

        values = [
            self.ui.tableWidget.item(row, col).text()
            for col in range(self.ui.tableWidget.columnCount())
        ]

        dialog = DynamicDialog(self.columns, values)

        if dialog.exec():
            new_values = dialog.get_data()
            set_clause = ", ".join([f"{col}=?" for col in self.columns])
            row_id = values[0]
            
            query = f'UPDATE "{self.current_table}" SET {set_clause} WHERE {self.columns[0]}=?'
            new_values.append(row_id)

            self.cursor.execute(query, new_values)
            self.conn.commit()
            self.load_table(self.current_table)

    def deleteRow(self):
        selected = self.ui.tableWidget.selectedItems()

        if not selected:
            return

        row = selected[0].row()
        row_id = self.ui.tableWidget.item(row, 0).text()

        self.cursor.execute(
            f'DELETE FROM "{self.current_table}" WHERE {self.columns[0]}=?',
            (row_id,)
        )

        self.conn.commit()
        self.load_table(self.current_table)

    def search_text(self):
        text = self.ui.lineEdit.text().lower()

        for row in range(self.ui.tableWidget.rowCount()):
            match = False
            for col in range(self.ui.tableWidget.columnCount()):
                item = self.ui.tableWidget.item(row, col)
                if item and text in item.text().lower():
                    match = True
                    break

            self.ui.tableWidget.setRowHidden(row, not match)

    def sort_table(self):
        index = self.ui.comboBox.currentIndex()
        
        if index >= 0:
            self.ui.tableWidget.sortItems(index, QtCore.Qt.AscendingOrder)
