# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from individ_main import MainWindow

LOGIN = "admin"
PASSWORD = "12345"

style = """
QPushButton{
border:2px solid rgb(0,255,0);
}

QComboBox{
border:2px solid rgb(0,255,0);
}

QLineEdit{
border:2px solid rgb(0,255,0);
}

QTableWidget{
border:2px solid rgb(0,255,0);
gridline-color:rgb(0,255,0);
}

QHeaderView::section{
border:1px solid rgb(0,255,0);
}
"""


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 400)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-color: rgb(0, 255, 0);")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 30, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 220, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 290, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход"))
        self.label.setText(_translate("MainWindow", "Войти в программу"))
        self.label_2.setText(_translate("MainWindow", "Логин"))
        self.label_3.setText(_translate("MainWindow", "Пароль"))
        self.pushButton.setText(_translate("MainWindow", "Войти"))


class LoginWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.pushButton.clicked.connect(self.check_login)

    def check_login(self):
        login = self.ui.lineEdit.text()
        password = self.ui.lineEdit_2.text()

        if login == LOGIN and password == PASSWORD:
            self.main = MainWindow()
            self.main.show()
            self.close()

        else:
            QtWidgets.QMessageBox.warning(self, "Ошибка", "Неверный логин или пароль")


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(style)
    window = LoginWindow()
    window.show()
    sys.exit(app.exec_())
